# Generated by Django 4.1.3 on 2023-01-16 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_cate', models.CharField(choices=[("Men's Dresses", "Men's Dresses"), ("Women's Dresses", "Women's Dresses"), ("Baby's Dresses", "Baby's Dresses")], max_length=100)),
                ('dressess_cate', models.CharField(choices=[('Shirt', 'Shirt'), ('Jeans', 'Jeans'), ('Swimwear', 'Swimwear'), ('Sleepwear', 'Sleepwear'), ('Sportwear', 'Sportwear'), ('Jumpsuits', 'Jumpsuits'), ('Blazers', 'Blazers'), ('Jackets', 'Jackets'), ('Shoes', 'Shoes')], max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.PositiveIntegerField()),
                ('product_desc', models.TextField()),
                ('product_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('ALL', 'ALL')], max_length=100)),
                ('product_pic', models.ImageField(upload_to='product_pic/')),
                ('product_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
