# Generated by Django 4.1.3 on 2023-02-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_wishlist_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price_shipping',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
