# Generated by Django 4.1.3 on 2023-02-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_shipping_address_billing_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billing_Address',
        ),
    ]
