# Generated by Django 4.1.3 on 2023-02-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price_shipping',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
